### ISSUE TITLE
Support additionalProperties: false

### ISSUE THREAD

**Issue by rubas** [ostrowr/ts-json-validator#21]
It looks like `additionalProperties: false` is not supported.

**Type 'false' is not assignable to type 'SchemaLike | undefined'**

**Comment by ostrowr** [comment]
Thanks! Yeah, I just haven't gotten around to implement this yet, but will ASAP. PRs also welcome :) 

I'm going to close this as a duplicate of #5 but feel free to comment on that with any more context.

**Comment by ostrowr** [comment]
This should be solved with the PR I just merged; I'll cut another release shortly.
