### ISSUE TITLE
Please upgrade AJV to at least version 6.12.3 to address vulnerabilities in the package.

### ISSUE THREAD

**Issue by funkel1989** [ostrowr/ts-json-validator#38]
- [X] Before submitting a bug report, double-check that your Typescript version is at least 3.7.

**Describe the bug**
Snyk has discovered vulnerabilities in the version of AJV used in your package. Please update your version of AJV.
https://snyk.io/vuln/SNYK-JS-AJV-584908

**Comment by ostrowr** [comment]
Thanks for your patience here! I'll cut a release shortly.
